name: ai_guardian
description: "A woman's safety app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  google_fonts: ^6.2.1
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.5
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo_extended.png
    - assets/images/onboarding.png
    - assets/images/login.png
    - assets/images/dashboard_sos.png
    - assets/images/dashboard_emergency_sms.png
    - assets/images/dashboard_help_bot.png
    - assets/images/dashboard_safe_shaker.png
    - assets/images/dashboard_track_me.png
    - assets/images/dashboard_support.png
    - assets/images/logo.png
    - assets/images/lobby_carousel_1.png
    - assets/images/lobby_carousel_2.png
    - assets/images/lobby_carousel_3.png
